package certs

import (
	"crypto/ecdsa"
	"crypto/elliptic"
	"crypto/x509"
	"os"
	"path/filepath"
	"testing"
	"time"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// TestGenerateCA_Properties verifies generated certificate has correct properties.
func TestGenerateCA_Properties(t *testing.T) {
	is := assert.New(t)
	must := require.New(t)

	m := &Manager{}
	cert, key, err := m.generateCA()
	must.NoError(err)
	must.NotNil(cert)
	must.NotNil(key)

	// Verify subject
	is.Equal("aiproxy self-signed ca", cert.Subject.CommonName)
	is.Equal([]string{"aiproxy ca"}, cert.Subject.Organization)

	// Verify CA flags
	is.True(cert.IsCA)
	is.True(cert.BasicConstraintsValid)
	is.Equal(0, cert.MaxPathLen)
	is.True(cert.MaxPathLenZero)

	// Verify key usage
	is.Equal(x509.KeyUsageCertSign|x509.KeyUsageCRLSign, cert.KeyUsage)

	// Verify serial number is set and non-zero
	is.NotNil(cert.SerialNumber)
	is.True(cert.SerialNumber.Sign() > 0)

	// Verify 10-year validity
	now := time.Now()
	is.True(cert.NotBefore.Before(now) || cert.NotBefore.Equal(now))
	is.WithinDuration(now.AddDate(10, 0, 0), cert.NotAfter, 24*time.Hour)

	// Verify ECDSA P-256
	is.Equal(elliptic.P256(), key.Curve)

	// Verify key pair matches
	certPub, ok := cert.PublicKey.(*ecdsa.PublicKey)
	must.True(ok)
	is.True(certPub.Equal(&key.PublicKey))

	// Verify SubjectKeyId is set (auto-generated by x509.CreateCertificate when nil and IsCA=true)
	is.NotEmpty(cert.SubjectKeyId)
}

// TestSaveCA_FilePermissions verifies correct file permissions after save.
func TestSaveCA_FilePermissions(t *testing.T) {
	is := assert.New(t)
	must := require.New(t)

	tmpDir := t.TempDir()
	certsDir := filepath.Join(tmpDir, "certs")

	// Create certs directory (now required before saveCA)
	must.NoError(os.MkdirAll(certsDir, 0750))

	certPath := filepath.Join(certsDir, "ca-cert.pem")
	keyPath := filepath.Join(certsDir, "ca-key.pem")

	m := NewManager(certPath, keyPath, false)
	cert, key, err := m.generateCA()
	must.NoError(err)

	err = m.saveCA(cert, key)
	must.NoError(err)

	// Verify certificate file has 0644 permissions
	certInfo, err := os.Stat(m.certPath)
	must.NoError(err)
	is.Equal(os.FileMode(0644), certInfo.Mode().Perm())

	// Verify key file has 0600 permissions
	keyInfo, err := os.Stat(m.keyPath)
	must.NoError(err)
	is.Equal(os.FileMode(0600), keyInfo.Mode().Perm())
}

// TestSaveCA_MissingDirectory verifies error when directory doesn't exist.
func TestSaveCA_MissingDirectory(t *testing.T) {
	must := require.New(t)

	tmpDir := t.TempDir()
	certsDir := filepath.Join(tmpDir, "nonexistent", "dirs", "certs")

	// Do NOT create directory - should fail

	certPath := filepath.Join(certsDir, "ca-cert.pem")
	keyPath := filepath.Join(certsDir, "ca-key.pem")

	m := NewManager(certPath, keyPath, false)
	cert, key, err := m.generateCA()
	must.NoError(err)

	err = m.saveCA(cert, key)
	must.Error(err)
	must.Contains(err.Error(), "failed to write certificate file")
}
