package certs

import (
	"crypto/ecdsa"
	"crypto/elliptic"
	"crypto/rand"
	"crypto/x509"
	"crypto/x509/pkix"
	"encoding/pem"
	"fmt"
	"log/slog"
	"math/big"
	"os"
	"time"
)

// generateCA creates a new ECDSA P-256 CA certificate.
func (m *Manager) generateCA() (*x509.Certificate, *ecdsa.PrivateKey, error) {
	// Generate ECDSA P-256 private key
	privateKey, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	if err != nil {
		return nil, nil, fmt.Errorf("failed to generate ECDSA key: %w", err)
	}

	// Generate 128-bit random serial number (RFC 5280 compliant)
	serialNumberLimit := new(big.Int).Lsh(big.NewInt(1), 128)
	serialNumber, err := rand.Int(rand.Reader, serialNumberLimit)
	if err != nil {
		return nil, nil, fmt.Errorf("failed to generate serial number: %w", err)
	}

	// Certificate template with required CA extensions
	template := &x509.Certificate{
		SerialNumber: serialNumber,
		Subject: pkix.Name{
			Organization: []string{"aiproxy ca"},
			CommonName:   "aiproxy self-signed ca",
		},
		NotBefore: time.Now(),
		NotAfter:  time.Now().AddDate(10, 0, 0), // 10 years validity

		// CA-specific extensions
		KeyUsage:              x509.KeyUsageCertSign | x509.KeyUsageCRLSign,
		BasicConstraintsValid: true,
		IsCA:                  true,
		MaxPathLen:            0,
		MaxPathLenZero:        true,

		// SubjectKeyId is auto-generated by x509.CreateCertificate when nil and IsCA=true
	}

	// Self-sign the certificate (parent == template for CA root)
	certDER, err := x509.CreateCertificate(
		rand.Reader,
		template,
		template, // self-signed
		&privateKey.PublicKey,
		privateKey,
	)
	if err != nil {
		return nil, nil, fmt.Errorf("failed to create certificate: %w", err)
	}

	// Parse the generated certificate
	cert, err := x509.ParseCertificate(certDER)
	if err != nil {
		return nil, nil, fmt.Errorf("failed to parse generated certificate: %w", err)
	}

	return cert, privateKey, nil
}

// saveCA writes certificate and key to PEM files with proper permissions.
// The certificate directory must already exist (validated at startup).
func (m *Manager) saveCA(cert *x509.Certificate, key *ecdsa.PrivateKey) error {
	// Encode certificate to PEM
	certPEM := encodeCertificatePEM(cert)

	// Write certificate file (0644 permissions - public data)
	if err := os.WriteFile(m.certPath, certPEM, 0644); err != nil {
		return fmt.Errorf("failed to write certificate file: %w", err)
	}

	// Encode private key to PEM
	keyPEM, err := encodeKeyPEM(key)
	if err != nil {
		return fmt.Errorf("failed to encode private key: %w", err)
	}

	// Write private key file with restrictive permissions (0600)
	if err := os.WriteFile(m.keyPath, keyPEM, 0600); err != nil {
		return fmt.Errorf("failed to write private key file: %w", err)
	}

	// Ensure key permissions are correct (defense in depth)
	if err := os.Chmod(m.keyPath, 0600); err != nil {
		return fmt.Errorf("failed to set private key permissions: %w", err)
	}

	slog.Debug("ca certificate files saved",
		"cert", m.certPath,
		"key", m.keyPath,
	)

	return nil
}

// encodeCertificatePEM encodes an x509 certificate to PEM format.
func encodeCertificatePEM(cert *x509.Certificate) []byte {
	return pem.EncodeToMemory(&pem.Block{
		Type:  "CERTIFICATE",
		Bytes: cert.Raw,
	})
}

// encodeKeyPEM encodes an ECDSA private key to PEM format.
func encodeKeyPEM(key *ecdsa.PrivateKey) ([]byte, error) {
	keyBytes, err := x509.MarshalECPrivateKey(key)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal private key: %w", err)
	}
	return pem.EncodeToMemory(&pem.Block{
		Type:  "EC PRIVATE KEY",
		Bytes: keyBytes,
	}), nil
}
